services:
- type: web
  name: sport-predictor
  env: python
  plan: free
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn --chdir web app:app
  envVars:
  - key: PORT
    value: 5000
  - key: FLASK_ENV
    value: production
  healthCheckPath: /
  crons:
  - name: update-all-sports
    schedule: "0 0,4,8,12,16,20 * * *"
    command: python refresh_data.py
