services:
- type: web
  name: sport-predictor
  env: python
  plan: free
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app --timeout 120 --workers 1 --threads 4
  envVars:
  - key: FLASK_ENV
    value: production
  - key: ODDS_API_KEY
    sync: false
  - key: REFRESH_INTERVAL
    value: "7200"
  healthCheckPath: /
